
uint64 timestamp		# time since system start (microseconds)

uint64 timestamp_sample		# the timestamp of the raw data (microseconds)

uint32 differential_pressure_device_id		# unique device ID for the selected differential pressure sensor

float32 indicated_airspeed_m_s		# indicated airspeed in m/s

float32 true_airspeed_m_s		# true filtered airspeed in m/s

float32 air_temperature_celsius		# air temperature in degrees celsius, -1000 if unknown
